# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    container_name: postgres_container
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ~/Documentos/UnB/Disciplinas/2024-1-EducaMinas-backend/Database/postgres:/data/postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: s40028922
      POSTGRES_DB: base_de_dados
      PGDATA: /data/postgres
    ports:
      - "5432:5432"

  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db

networks:
  default:
    driver: bridge
